### PR TITLE
Add support for Swissbit cards

### PR DESCRIPTION
**Pull request by J-Twin**
Hello,

Vendor provides documentation upon registration.

Compiled and tested using a brand new S-56u Gen 5 card on my T6 ARM board:

{
"version": "abc222",
"date": "2023-12-11T22:30:49.000Z",
"device":"/dev/mmcblk0",
"addTime": "false",
"signature":"0x53 0x77",
"Swissbit":"true",
"fwVersion": [W,0,1,1,2, ,,,,,,,,,,],
"User area rated cycles": ["0x00","0x01","0x86","0xa0"], "User area max cycle cnt": ["0x00","0x00","0x00","0x03"], "User area total cycle cnt": ["0x00","0x00","0x08","0xb6"], "User area average cycle cnt": ["0x00","0x00","0x00","0x01"], "System area max cycle cnt": ["0x00","0x00","0x00","0x01"], "System area total cycle cnt": ["0x00","0x00","0x00","0x28"], "System area average cycle cnt": ["0x00","0x00","0x00","0x00"], "Remaining Lifetime Percent": 99%,
"Speed mode": SDR104 speed
"Bus width": 4 bits
"User area spare blocks cnt": ["0x00","0x00","0x01","0xe2"], "System area spare blocks cnt": ["0x00","0x00","0x00","0x63"], "User area runtime bad blocks cnt": ["0x00","0x00","0x00","0x00"], "System area runtime bad blocks cnt": ["0x00","0x00","0x00","0x00"], "User area refresh cnt": ["0x00","0x00","0x00","0x00"], "System area refresh cnt": ["0x00","0x00","0x00","0x00"], "Interface crc cnt": ["0x00","0x00","0x00","0x00"], "Power cycle cnt": ["0","0","0","19"],
"success":true
}

### CODE REVIEW

**Comment by vladkozlov69** [comment]
@J-Twin looks like we can use nword_to_int function to decode four-byte values like "User area rated cycles" etc. to make them easily readable )

**Comment by Ognian** [comment]
Thanks a lot!

**Comment by Ognian** [comment]
@J-Twin I've merged and reformatted your code. Could you, as @vladkozlov69 suggested use the bytes_to_int function? It would make it better readable.

**Comment by J-Twin** [comment]
Hello,

I am OK with the current but will check power cycle values once they fill the first byte. If it does not look OK I will change it. You are free to do it now if you wish.

One newline is missing now with the latest version and a % after the lifetime percentage:

sudo ./sdmon /dev/mmcblk0
{
"version": "v0.7.0-3 (1613eeb) arm64",
"date": "2023-12-12T19:00:27.000Z",
"device":"/dev/mmcblk0",
"addTime": "false",
"signature":"0x53 0x77",
"Swissbit":"true",
"fwVersion": [W,0,1,1,2, ,,,,,,,,,,],
"User area rated cycles": ["0x00","0x01","0x86","0xa0"],
"User area max cycle cnt": ["0x00","0x00","0x00","0x03"],
"User area total cycle cnt": ["0x00","0x00","0x08","0xb6"],
"User area average cycle cnt": ["0x00","0x00","0x00","0x01"],
"System area max cycle cnt": ["0x00","0x00","0x00","0x01"],
"System area total cycle cnt": ["0x00","0x00","0x00","0x28"],
"System area average cycle cnt": ["0x00","0x00","0x00","0x00"],
"Remaining Lifetime Percent": 99"Speed mode": SDR104 speed
"Bus width": 4 bits
"User area spare blocks cnt": ["0x00","0x00","0x01","0xe2"],
"System area spare blocks cnt": ["0x00","0x00","0x00","0x63"],
"User area runtime bad blocks cnt": ["0x00","0x00","0x00","0x00"],
"System area runtime bad blocks cnt": ["0x00","0x00","0x00","0x00"],
"User area refresh cnt": ["0x00","0x00","0x00","0x00"],
"System area refresh cnt": ["0x00","0x00","0x00","0x00"],
"Interface crc cnt": ["0x00","0x00","0x00","0x00"],
"Power cycle cnt": ["0","0","0","20"],
"success":true
}

**Comment by Ognian** [comment]
% should be now correct... can you retest?

**Comment by J-Twin** [comment]
Hello,

It is correct now. I am getting similar results compared to my initial custom version.

Going for the next one.

**Pull request merged**
